name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.1
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_icons_plus: ^1.0.3
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app logo.png"

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils/app_assets/images
  filename: app_images.dart
  field_prefix:    

# flutter_assets:
#   assets_path: assets/animations
#   output_path: lib/core/utils/app_assets/animations
#   filename: app_animations.dart
#   field_prefix:    